### ISSUE TITLE
json_nl: Emit newlines immediately, rather than waiting for next stream item

### ISSUE THREAD

**Issue by sartak** [abdolence/axum-streams-rs#21]
Hi, thanks for axum-streams-rs. I noticed that the newline-delimited JSON format emits the newline separator before each item (except for the very first). This makes it harder to use than if every object were immediately followed by a newline.

On the consumer side, the natural, easy way to handle newline-delimited JSON (in general) is to buffer the response until you see a newline, then pass that off to `JSON.parse`. If you do that with the current implementation of this library, you'll always be delayed by the latency of the next message, and you'd potentially miss the very last message (unless you handle the edge case of a valid JSON object with no newline on stream close). So you'd need a more sophisticated response, such as _trying_ to parse the buffer as JSON each time you get more content on the TCP stream, which is more expensive and complicated.

Relatedly, https://github.com/ndjson/ndjson-spec#31-serialization states "Each JSON text MUST […] be written to the stream followed by the newline character `\n`".

Please consider changing this code to emit the newline immediately after each object, unconditionally. https://github.com/abdolence/axum-streams-rs/blob/f48d9881ce12bb2f4158d239317a4ff7f249b687/src/json_formats.rs#L81-L87

**Comment by abdolence** [comment]
Hey,

Interesting finding. So the problem actually happens only if we have one element to emit, so in this case it will be emitted without `\n`. Let me look into this.

**Comment by sartak** [comment]
Thank you, works great! 😄
