### ISSUE TITLE
Make StreamFormat trait public.

### ISSUE THREAD

**Issue by WIGGLES-dev** [abdolence/axum-streams-rs#35]
Cool crate,

I don't know if you had a convincing reason to make StreamFormat private, but I immediately had a use case where non of your provided formats would be ideal.

I would suggest making it public..

**Comment by abdolence** [comment]
Hey,

No, there wasn't any particular reason except it was mostly used internally, but if someone wants to use it to make their own formats, I'm happy to open it.

https://github.com/abdolence/axum-streams-rs/commit/0f627f50dbada2c8fb16be0bb128ce33a76187ce
