### ISSUE TITLE
Customizing frame size

### ISSUE THREAD

**Issue by happysalada** [abdolence/axum-streams-rs#37]
Hi, I've had a look at the library and it seems one http frame is generated per object
https://github.com/abdolence/axum-streams-rs/blob/master/src/json_formats.rs#L58
would you consider being able to customize frame size ?
I believe it's common practice to have frames of 4 to 16 kb when sending streams on http to try to be efficient.
Let me know if anything doesn't make sense!

**Comment by abdolence** [comment]
Hi, makes sense to have some configuration, I agree. 
I'm not sure if something was changed recently in hyper, but they had their own buffering, so it should help even before this optimisation.

**Comment by happysalada** [comment]
hey just a small update on this. I was trying the now Body::from_stream provided by axum in the 0.7 version
I had a stream with a result. I just found out that errors in the stream are not well handled by axum when you serve it with hyper. They just cut the connection.
I'm going to wait a bit until axum stabilizes the Body trait.
I'll be back though.

**Comment by abdolence** [comment]
I've prepared this PR to improve this area:

https://github.com/abdolence/axum-streams-rs/pull/40

This is not exactly the frame size in bytes, but should help I guess in most cases?

**Comment by abdolence** [comment]
So, the usage will be something like this:

```rust
    StreamBodyAs::options(StreamBodyAsOptions::new().buffering_items(1000))
        .json_array(source_test_stream())
```

which means that the frame will contain up to 1000 items if they are ready at the moment the frame was created.

**Comment by happysalada** [comment]
That's a nice improvement that paves the way for the byte size buffering, thank you!
