### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by kyle-leonhard** [abdolence/axum-streams-rs#54]
Hey, how is one meant to handle streams that might produce errors via `Result` while streaming?

For example, using SQLX, one might use `fetch` to stream results back from a database:

```
async fn stream_results(Extension(pool): Extension<&'static PgPool>) -> impl IntoResponse {
    let tasks = sqlx::query_as("SELECT some_column from some_table")
        .fetch(pool)
        // This drops any errors!
        .filter_map(|t: Result<SomeStruct, sqlx::Error>| t.ok());

    StreamBodyAs::json_array(tasks)
)
```

**Comment by abdolence** [comment]
Hey, this question is more like about rust `Stream`s in general, so you kind of free to go with any suitable option for you.

Commonly, errors in the middle are system errors, and if you just want to log the error and finish the stream, so you can go with

`
 .take_while(|item| item.is_ok())
 .filter_map(|item| item.ok()) // better to have logs of course here
`

if you have a client that able to handle errors in stream in `filter_map` you can convert your result into something that indicates it.

**Comment by abdolence** [comment]
Closing this, let me know if the answer is not clear or you have other questions.

**Comment by abdolence** [comment]
This is why I mentioned that in `filter_map` you can convert your result into something that indicates it.
So, you can introduce some error structure or field that indicates the error occured so that the last element will contain that.
This requires though that client expect some error handling on their side.

Trailing headers is too late, since they already sent before an error occurs.

**Comment by abdolence** [comment]
`Result` is not something serializable in Rust, so can't be handled that flexible on the library side in this case. What if you want to introduce your own serializable Enum or a field to indicate errors? I'm open to any suggestion though if you see a generic way to indicate errors (except closing the connection/stream in progress). Just remember though that HTTP headers and statuses already sent, so we can't change that while producing items.

**Comment by abdolence** [comment]
Ah, right the trailing headers (I missed the important part in your suggestion, sorry :D).

This is interesting. Let me contemplate on it. Maybe it is beneficial to be able to do that for some protocols additionally to the application level protocol.

**Comment by abdolence** [comment]
I'll check trailer capabilities in Axum and also Axum error handling itself. Maybe it is better to propagate some error to Axum in some cases which will indicate issues on connection level.

Thanks for a great suggestion with trailers.
I'll come back to you after some experiments with Axum.

**Comment by abdolence** [comment]
I just merged the support of error propagation support into the master branch, so you can do this:

https://github.com/abdolence/axum-streams-rs/blob/b13feeef6d3a1a6a3d790fff75f4a26516a2c22e/examples/json-with-errors-example.rs#L26C4-L26C22

Seems it should cover the most common case and connection will be aborted on Axum level (the clients should detect it). It doesn't have any fancy stuff like trailing headers and some additional statuses, but I think it should cover the common issues.

**Comment by abdolence** [comment]
Tested it with a chrome browser and cURL, and they seem detects those as `ERR_INCOMPLETE_CHUNKED_ENCODING` on the connection level.

**Comment by abdolence** [comment]
Yes, it is a manual work. There is only one maintainer :) I'll release it a bit later after some additional verification.

**Comment by abdolence** [comment]
However cargo has a capability to refer directly to GitHub for the versions that not released yet, so nothing stop people use it until then.

**Comment by abdolence** [comment]
Released in https://github.com/abdolence/axum-streams-rs/releases/tag/v0.17.0
