### ISSUE TITLE
html version?

### ISSUE THREAD

**Issue by bbigras** [abdolence/axum-streams-rs#55]
Could a html version be added?

**Comment by abdolence** [comment]
Hi,
What is an example/use case of HTML version? How clients should handle those streams?

Other formats used in real world to stream relatively big number of items in a stream.
The streaming approach is not so valuable it is a small piece of free form text which can't be handled until you finish reading.

**Comment by bbigras** [comment]
> How clients should handle those streams?

Browsers seem to support it, so you can do something like:

```rust
async fn index() -> impl IntoResponse {
    use tokio::time::{sleep, Duration};
    let stream = async_stream::stream! {
        for i in 0..10 {
            yield async { format!("<p>Hello, {}</p>", i) }.await;
            sleep(Duration::from_millis(1000)).await;
        }
    };

    StreamBodyAs::text(stream)
}
```

> What is an example/use case of HTML version?

If somebody make a rust template engine like https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Template.generate_async .

Rendering a normal template must be pretty fast so I don't know if it would be worth it.

With async rendering, you could have something like (note that the footer is blocked until the end):

https://youtu.be/kYV8K71pY64?t=1560

**Comment by bbigras** [comment]
and with this:

```rust

async fn index() -> impl IntoResponse {
    let part1 = r#"
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Streaming example</title>
  </head>
  <body>                                              
    <div>
      <template shadowrootmode="open">
        <header>Header</header>
        <main>
          <slot name="content1">
            <div style="height: 50px">Loading...</div>
          </slot>

        </main>
        <footer>Footer</footer>
      </template>
"#;

    let part2 = r#"
    <div slot="content1">
      <div  style="height: 50px;">Done!</div>
    </div>
  </div>
</body>
</html>
"#;

    use tokio::time::{sleep, Duration};
    let stream = async_stream::stream! {
        yield async { part1.to_string() }.await;
        yield async {
            sleep(Duration::from_millis(1500)).await;
            part2.to_string()
        }.await;
    };

    StreamBodyAs::text(stream)
}
```

you can have:

[Kooha-2024-06-19-11-10-16.webm](https://github.com/abdolence/axum-streams-rs/assets/24027/dfb0b50f-105a-4f30-8077-6273e7bfc55a)

I saw that first in that blog post [Streaming HTML out of order without JavaScript](https://lamplightdev.com/blog/2024/01/10/streaming-html-out-of-order-without-javascript/).

**Comment by abdolence** [comment]
I see, thanks for the examples, of course it is supported by browsers (since the content is the same). 

So, the only question is that HTML pages commonly small in sizes, and I'm not sure if any benefits can be gain from this approach in real life.

What I can do probably though, I can extend `StreamBodyAs::text(stream)` in a way you can specify content type additionally and send any possible text formats.

**Comment by bbigras** [comment]
> I can extend `StreamBodyAs::text(stream)` in a way you can specify content type additionally and send any possible text formats.

That would be great, thanks.

**Comment by abdolence** [comment]
Starting with v0.16.0 now you can override default content type generated by all formats.

An example for text format:
```rust
StreamBodyAsOptions::new()
        .content_type(HttpHeaderValue::from_static("text/plain; charset=utf-8"))
        .text(source_test_stream())
```
