### ISSUE TITLE
Arrow streaming without schema

### ISSUE THREAD

**Issue by domoritz** [abdolence/axum-streams-rs#60]
I have a stream of record batches that I want to send but I don't have access to the schema easily. Would it make sense to have an API that just takes a stream of batches and gets the schema from the first batch?

**Comment by abdolence** [comment]
Hey. Correct me if I'm wrong but not sure if it is possible since IPC stream requires it.

Probably as a workaround you can just send some kind of dummy schema?

**Comment by abdolence** [comment]
Reading here though:
https://arrow.apache.org/docs/format/Columnar.html#serialization-and-interprocess-communication-ipc

Seems it is not defined as required. Then probably it is a good idea to have it optionally.

**Comment by abdolence** [comment]
If you want to give a try, you can check this PR:
https://github.com/abdolence/axum-streams-rs/pull/61

refering to GitHub branch in your Cargo.toml

**Comment by abdolence** [comment]
Schema-less is not possible though to use using the official Apache Arrow implementation  API for Rust. So, they treat it as required.

![image](https://github.com/user-attachments/assets/5a91df46-6608-4233-a4cc-685de8068eac)

**Comment by domoritz** [comment]
Doesn't make sense as explained in https://github.com/abdolence/axum-streams-rs/pull/61#issuecomment-2290978928
