### ISSUE TITLE
Generate docs with features enabled?

### ISSUE THREAD

**Issue by cbeck88** [abdolence/axum-streams-rs#62]
For the latest docs, for example here: https://docs.rs/axum-streams/0.18.0/axum_streams/

None of the features are enabled for the docs build, so that makes it hard to figure out how to use it for json, or csv, etc. without looking at the source code instead, since you can't see the docs for any of that. I think you just have to set a flag in your Cargo.toml so that rustdoc will enable all the features when it runs

**Comment by abdolence** [comment]
Yes, it was forgotten. Will publish it in a few days.

**Comment by abdolence** [comment]
This is fixed now in https://github.com/abdolence/axum-streams-rs/releases/tag/v0.18.1
